service: aws-serverles-crud

frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-latest-layer-version # for developers
  - serverless-pseudo-parameters # for developers
  - serverless-offline # for developers

package:
  exclude:
    - "**/node_modules/**"  # all node_modules folder
    - "**/*.test.*"  # all test files
    - ".dynamodb/**"
    - ".serverless/**"
  include:
    - src/module/actor/createActor.js
    - src/module/actor/deleteActor.js
    - src/module/actor/getActor.js
    - src/module/actor/getMultiActor.js
    - src/module/actor/updateActor.js

provider:
  name: aws
  runtime: nodejs12.x # node package version
  stage: ${opt:stage, 'dev'} # default invironment set to (dev = "development stage")
  region: ${opt:region, 'us-east-1'} # region where it will be deploy
  deploymentBucket:
    name: deploy.${self:provider.region}.nipahut.club # S3 bucket name
  environment:
    DEPLOYMENT_STAGE: ${self:provider.stage} # staging environment dev, test or prod
    WORKFLOW_ACTOR_TABLE: workflow_actor-${self:provider.stage} # actors table service
    NODE_PATH: './:/opt/node_modules' # node modules layer path

functions:
# Updload PDF file only
  createActor:
    description: create actor
    handler: src/module/actor/createActor.handler
    layers:
      - arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:layer:aws-serverles-layers-module-${self:provider.stage}:latest
    events:
      - http:
          path: /upload
          method: post
          cors: true
